use_frameworks!

platform :ios, '9.0'

target 'HQCyclePagerView_Example' do
  pod 'HQCyclePagerView', :path => '../'

  target 'HQCyclePagerView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
